<a href="https://colab.research.google.com/github/KS6Git/Python_EDA_Raja/blob/main/Adaboost_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Adaboost Assignment**
**Problem Statement:
This assignment aims to utilize the AdaBoost algorithm to analyze given datasets, extract meaningful insights, and predict outcomes based on the ensemble of weak learners. By exploring the datasets and employing AdaBoost techniques, students are expected to build predictive models and interpret the ensemble learning process to derive valuable insights.**

##1. Importing necessary libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

##2. Loading the Dataset: Brain_stroke

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Raja_Python_Programming/Adaboost/brain_stroke.csv')

##3. Summarising the Dataset

Attribute Information

1) gender: "Male", "Female" or "Other"

2) age: age of the patient

3) hypertension: 0 if the patient doesn't have hypertension, 1 if the patient has hypertension

4) heart disease: 0 if the patient doesn't have any heart diseases, 1 if the patient has a heart disease 5) Ever-married: "No" or "Yes"

6) work type: "children", "Govtjov", "Never worked", "Private" or "Self-employed"

7) Residencetype: "Rural" or "Urban"

8) avg glucose level: average glucose level in blood

9) BMI: body mass index

10) smoking_status: "formerly smoked", "never smoked", "smokes" or "Unknown"*

11) stroke: 1 if the patient had a stroke or 0 if not

In [ ]:
data.head(2)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1

In [ ]:
data.shape

(4981, 11)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             4981 non-null   object
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64
 3   heart_disease      4981 non-null   int64
 4   ever_married       4981 non-null   object
 5   work_type          4981 non-null   object
 6   Residence_type     4981 non-null   object
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object
 10  stroke             4981 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB

In [ ]:
data.describe()

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,4981.000000,4981.000000,4981.000000,4981.000000,4981.000000,4981.000000
mean,43.419859,0.096165,0.055210,105.943562,28.498173,0.049789
std,22.662755,0.294848,0.228412,45.075373,6.790464,0.217531
min,0.080000,0.000000,0.000000,55.120000,14.000000,0.000000
25%,25.000000,0.000000,0.000000,77.230000,23.700000,0.000000
50%,45.000000,0.000000,0.000000,91.850000,28.100000,0.000000
75%,61.000000,0.000000,0.000000,113.860000,32.600000,0.000000
max,82.000000,1.000000,1.000000,271.740000,48.900000,1.000000

##4. Pre-processing the Dataset

In [ ]:
data.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
data.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [ ]:
data['gender']

0         Male
1         Male
2       Female
3       Female
4         Male
         ...
4976      Male
4977      Male
4978    Female
4979      Male
4980    Female
Name: gender, Length: 4981, dtype: object

In [ ]:
# convert the gender column to 1 & 0
data['gender'] = data['gender'].map({'Male': 1, 'Female': 0})

**Another way to Convert the Male/Female to 1 & 0**              
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data['gender'] = le.fit_transform(data['gender'])

In [ ]:
data['gender']

0       1
1       1
2       0
3       0
4       1
       ..
4976    1
4977    1
4978    0
4979    1
4980    0
Name: gender, Length: 4981, dtype: int64

In [ ]:
data.head(2)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,1,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1

In [ ]:
print(data.columns)

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [ ]:
# Another way to Convert the Male/Female to 1 & 0
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data['gender'] = le.fit_transform(data['gender'])

In [ ]:
data.keys()

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [ ]:
# need to convert 'smoker' to 1 and 'non-smoker' to 0
data['smoking_status'] = data['smoking_status'].map({'Yes': 1, 'No': 0})

In [ ]:
data.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67.0,0,1,Yes,Private,Urban,228.69,36.6,NaN,1
1,1,80.0,0,1,Yes,Private,Rural,105.92,32.5,NaN,1
2,0,49.0,0,0,Yes,Private,Urban,171.23,34.4,NaN,1
3,0,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,NaN,1
4,1,81.0,0,0,Yes,Private,Urban,186.21,29.0,NaN,1

In [ ]:
# convert 'ever_married' - Yes/No --> 1/0
data['ever_married'] = data['ever_married'].map({'Yes': 1, 'No': 0})

In [ ]:
# handle missing values
data['smoking_status'] = data['smoking_status'].fillna('Unknown')

In [ ]:
data.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67.0,0,1,NaN,Private,Urban,228.69,36.6,Unknown,1
1,1,80.0,0,1,NaN,Private,Rural,105.92,32.5,Unknown,1
2,0,49.0,0,0,NaN,Private,Urban,171.23,34.4,Unknown,1
3,0,79.0,1,0,NaN,Self-employed,Rural,174.12,24.0,Unknown,1
4,1,81.0,0,0,NaN,Private,Urban,186.21,29.0,Unknown,1

In [ ]:
# handle missing values
data['ever_married'] = data['ever_married'].fillna('Unknown')

In [ ]:
data['ever_married'] = data['ever_married'].fillna('Unknown')

data = pd.get_dummies(data, columns=['ever_married'], dtype=int)

In [ ]:
data.head()

,gender,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,work_type_Govt_job_False,work_type_Govt_job_True,work_type_Private_False,...,work_type_Self-employed_False,work_type_Self-employed_True,work_type_children_False,work_type_children_True,Residence_type_Rural_False,Residence_type_Rural_True,Residence_type_Urban_False,Residence_type_Urban_True,smoking_status_Unknown_True,ever_married_Unknown
0,1,67.0,0,1,228.69,36.6,1,1,0,0,...,1,0,1,0,1,0,0,1,1,1
1,1,80.0,0,1,105.92,32.5,1,1,0,0,...,1,0,1,0,0,1,1,0,1,1
2,0,49.0,0,0,171.23,34.4,1,1,0,0,...,1,0,1,0,1,0,0,1,1,1
3,0,79.0,1,0,174.12,24.0,1,1,0,1,...,0,1,1,0,0,1,1,0,1,1
4,1,81.0,0,0,186.21,29.0,1,1,0,0,...,1,0,1,0,1,0,0,1,1,1

In [ ]:
data = pd.get_dummies(data, columns=['work_type', 'Residence_type', 'smoking_status'])

In [ ]:
data.head()

,gender,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,work_type_Govt_job,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown
0,1,67.0,0,1,Unknown,228.69,36.6,1,False,True,False,False,False,True,True
1,1,80.0,0,1,Unknown,105.92,32.5,1,False,True,False,False,True,False,True
2,0,49.0,0,0,Unknown,171.23,34.4,1,False,True,False,False,False,True,True
3,0,79.0,1,0,Unknown,174.12,24.0,1,False,False,True,False,True,False,True
4,1,81.0,0,0,Unknown,186.21,29.0,1,False,True,False,False,False,True,True

In [ ]:
# convert to integers
data = pd.get_dummies(data, columns=['work_type_Govt_job', 'work_type_Private', 'work_type_Self-employed', 'work_type_children','Residence_type_Rural', 'Residence_type_Urban','smoking_status_Unknown'], dtype=int)

In [ ]:
data.head()

,gender,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,work_type_Govt_job_False,work_type_Govt_job_True,...,work_type_Private_True,work_type_Self-employed_False,work_type_Self-employed_True,work_type_children_False,work_type_children_True,Residence_type_Rural_False,Residence_type_Rural_True,Residence_type_Urban_False,Residence_type_Urban_True,smoking_status_Unknown_True
0,1,67.0,0,1,Unknown,228.69,36.6,1,1,0,...,1,1,0,1,0,1,0,0,1,1
1,1,80.0,0,1,Unknown,105.92,32.5,1,1,0,...,1,1,0,1,0,0,1,1,0,1
2,0,49.0,0,0,Unknown,171.23,34.4,1,1,0,...,1,1,0,1,0,1,0,0,1,1
3,0,79.0,1,0,Unknown,174.12,24.0,1,1,0,...,0,0,1,1,0,0,1,1,0,1
4,1,81.0,0,0,Unknown,186.21,29.0,1,1,0,...,1,1,0,1,0,1,0,0,1,1

In [ ]:
print(data.dtypes)

gender                             int64
age                              float64
hypertension                       int64
heart_disease                      int64
ever_married                      object
avg_glucose_level                float64
bmi                              float64
stroke                             int64
work_type_Govt_job_False           int64
work_type_Govt_job_True            int64
work_type_Private_False            int64
work_type_Private_True             int64
work_type_Self-employed_False      int64
work_type_Self-employed_True       int64
work_type_children_False           int64
work_type_children_True            int64
Residence_type_Rural_False         int64
Residence_type_Rural_True          int64
Residence_type_Urban_False         int64
Residence_type_Urban_True          int64
smoking_status_Unknown_True        int64
dtype: object

##5. Segregating the Dataset into Input and Output

In [ ]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [ ]:
x

array([[ 1., 67.,  0., ...,  0.,  1.,  1.],
       [ 1., 80.,  0., ...,  1.,  0.,  1.],
       [ 0., 49.,  0., ...,  0.,  1.,  1.],
       ...,
       [ 0., 45.,  1., ...,  1.,  0.,  1.],
       [ 1., 40.,  0., ...,  1.,  0.,  1.],
       [ 0., 80.,  1., ...,  0.,  1.,  1.]])

In [ ]:
y

array([1, 1, 1, ..., 1, 1, 1])

##6. Splitting the dataset into Train and Test

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x.shape, y.shape

((4981, 20), (4981,))

In [ ]:
x_train.shape,y_train.shape, x_test.shape,y_test.shape

((3984, 20), (3984,), (997, 20), (997,))

##7. Loading the Dataset

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier()

In [ ]:
model

AdaBoostClassifier()

##8. Training the Dataset

In [ ]:
model.fit(x_train,y_train)

AdaBoostClassifier()

##9. Predicting the data

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1])

##10. Calculate the accuracy of the trained model

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0

##11. Predicting output of single data using the trained model

In [ ]:
x_test[7]

array([  0.  ,  61.  ,   0.  ,   0.  , 115.42,  16.7 ,   0.  ,   1.  ,
         0.  ,   0.  ,   1.  ,   1.  ,   0.  ,   1.  ,   0.  ,   1.  ,
         0.  ,   0.  ,   1.  ,   1.  ])