<a href="https://colab.research.google.com/github/KS6Git/Python_EDA_Raja/blob/main/Random_Forest_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **RANDOM FOREST ASSIGNMENT**
Problem Statement:
This assignment aims to utilize Random Forest algorithms to analyze given datasets, extracting
meaningful insights, and predicting outcomes based on the decision rules learned from the data.
By exploring the datasets and employing Random Forest techniques, students are expected to
build predictive models and interpret the decision rules to derive valuable insights.

- Credit Risk Classification Dataset
https://www.kaggle.com/datasets/praveengovi/credit-risk-classification-dataset/data

##1. Importing necessary Libraries

In [42]:
import numpy as np
import pandas as pd

##2. Loading both the Payment & Customer datasets
https://www.kaggle.com/datasets/praveengovi/credit-risk-classification-dataset/data

In [43]:
Payment_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Raja_Python_Programming/Random_Tree/payment_data.csv')

In [44]:
Customer_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Raja_Python_Programming/Random_Tree/customer_data.csv')

**payment_data.csv:**
  
**id:** customer id     
**OVD_t1:** number of times overdue type 1  
**OVD_t2:** number of times overdue type 2  
**OVD_t3:** number of times overdue type 3    
**OVD_sum:** total overdue days   
**pay_normal:** number of times normal payment  
**prod_code:** credit product code  
**prod_limit:** credit limit of product   
**update_date:** account update date  
**new_balance:** current balance of product   
**highest_balance:** highest balance in history   
**report_date:** date of recent payment   

**customer_data.csv:**                              
customer’s card payment history.
customer’s demographic data and category attributes which have been encoded.                             
Category features are
**fea_1, fea_3, fea_5, fea_6, fea_7, fea_9.**   
**label is 1**, the customer is in high credit risk   
**label is 0**, the customer is in low credit risk

**customer_data.csv:**

customer’s demographic data and category        attributes which have been encoded.                                            
Category features are fea_1, fea_3, fea_5, fea_6, fea_7, fea_9.                                       
label is 1, the customer is in high credit risk     
label is 0, the customer is in low credit risk

In [49]:
Payment_data.head(3)

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,highest_balance,report_date
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,NaN,NaN
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,491100.0,NaN
2,58997200,0,0,0,0,2,5,NaN,04/12/2016,840000.0,700500.0,22/04/2016

In [53]:
Payment_data.shape

(8250, 12)

In [48]:
Customer_data.head(3)

,label,id,fea_1,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
0,1,54982665,5,1245.5,3,77000.0,2,15,5,109,5,151300,244.948974
1,0,59004779,4,1277.0,1,113000.0,2,8,-1,100,3,341759,207.173840
2,0,58990862,7,1298.0,1,110000.0,2,11,-1,101,5,72001,1.000000

In [52]:
Customer_data.shape

(1125, 13)

## **Merge the 2 datasets**

In [47]:
df = pd.merge(Payment_data, Customer_data, on='id')

In [50]:
df.head(3)

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,...,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,...,1241.0,3,62000.0,2,15,9,95,4,60023,1.000000
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,...,NaN,2,126000.0,2,11,9,115,4,450028,224.267697
2,58997200,0,0,0,0,2,5,NaN,04/12/2016,840000.0,...,1376.0,1,150000.0,2,11,-1,110,4,60000,219.248717

In [51]:
df.shape

(8250, 24)

##3. Summarising the Payment dataset

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8250 entries, 0 to 8249
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               8250 non-null   int64
 1   OVD_t1           8250 non-null   int64
 2   OVD_t2           8250 non-null   int64
 3   OVD_t3           8250 non-null   int64
 4   OVD_sum          8250 non-null   int64
 5   pay_normal       8250 non-null   int64
 6   prod_code        8250 non-null   int64
 7   prod_limit       2132 non-null   float64
 8   update_date      8224 non-null   object
 9   new_balance      8250 non-null   float64
 10  highest_balance  7841 non-null   float64
 11  report_date      7136 non-null   object
 12  label            8250 non-null   int64
 13  fea_1            8250 non-null   int64
 14  fea_2            7222 non-null   float64
 15  fea_3            8250 non-null   int64
 16  fea_4            8250 non-null   float64
 17  fea_5            8250 non-null   int64
 18  fea_6            8250 non-null   int64
 19  fea_7            8250 non-null   int64
 20  fea_8            8250 non-null   int64
 21  fea_9            8250 non-null   int64
 22  fea_10           8250 non-null   int64
 23  fea_11           8250 non-null   float64
dtypes: float64(6), int64(16), object(2)
memory usage: 1.5+ MB

In [15]:
df.describe()

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,new_balance,highest_balance,...,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
count,8.250000e+03,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,2132.000000,8.250000e+03,7.841000e+03,...,7222.000000,8250.000000,8.250000e+03,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000
mean,5.782173e+07,0.249091,0.127152,0.369212,187.681697,14.526667,8.232000,85789.702205,1.054042e+05,2.192027e+05,...,1286.156813,2.319636,1.386712e+05,1.940848,11.013939,4.881091,100.026303,4.245333,188575.384848,153.030672
std,1.822724e+06,1.250197,0.860046,2.900320,1804.232570,12.053627,3.533055,74345.828184,1.887704e+06,2.814536e+06,...,52.002429,0.887414,1.081565e+05,0.235922,2.694611,3.031902,12.540081,0.876647,167030.877718,122.082517
min,5.498235e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.100000,-4.030320e+04,5.010000e+02,...,1116.500000,1.000000,1.500000e+04,1.000000,3.000000,-1.000000,64.000000,1.000000,60000.000000,1.000000
25%,5.499050e+07,0.000000,0.000000,0.000000,0.000000,4.000000,6.000000,37400.000000,0.000000e+00,2.345300e+04,...,1248.500000,1.000000,7.700000e+04,2.000000,8.000000,5.000000,90.000000,3.000000,60047.000000,1.000000
50%,5.898905e+07,0.000000,0.000000,0.000000,0.000000,11.000000,10.000000,68200.000000,0.000000e+00,4.404700e+04,...,1283.000000,3.000000,1.110000e+05,2.000000,11.000000,5.000000,105.000000,5.000000,72000.000000,184.724119
75%,5.899655e+07,0.000000,0.000000,0.000000,0.000000,25.000000,10.000000,112200.000000,2.494800e+04,1.005000e+05,...,1317.500000,3.000000,1.510000e+05,2.000000,12.000000,5.000000,110.000000,5.000000,350020.000000,220.227156
max,5.900624e+07,34.000000,34.000000,35.000000,31500.000000,36.000000,27.000000,660000.000000,1.632120e+08,1.800005e+08,...,1481.000000,3.000000,1.200000e+06,2.000000,16.000000,10.000000,115.000000,5.000000,650070.000000,707.106781

In [16]:
df.shape

(8250, 24)

In [17]:
df.keys()

Index(['id', 'OVD_t1', 'OVD_t2', 'OVD_t3', 'OVD_sum', 'pay_normal',
       'prod_code', 'prod_limit', 'update_date', 'new_balance',
       'highest_balance', 'report_date', 'label', 'fea_1', 'fea_2', 'fea_3',
       'fea_4', 'fea_5', 'fea_6', 'fea_7', 'fea_8', 'fea_9', 'fea_10',
       'fea_11'],
      dtype='object')

##4. Pre-processing the Payment dataset

In [18]:
df.isnull().sum()

id                    0
OVD_t1                0
OVD_t2                0
OVD_t3                0
OVD_sum               0
pay_normal            0
prod_code             0
prod_limit         6118
update_date          26
new_balance           0
highest_balance     409
report_date        1114
label                 0
fea_1                 0
fea_2              1028
fea_3                 0
fea_4                 0
fea_5                 0
fea_6                 0
fea_7                 0
fea_8                 0
fea_9                 0
fea_10                0
fea_11                0
dtype: int64

**Clean the data - drop IDs, Handle missing values, fix dtypes**

In [ ]:
# Payment_data = Payment_data.drop(['id'],axis=1,inplace=True)
# Payment_data = Payment_data.fillna(Payment_data.mean(numeric_only=True))

In [54]:
df.keys()

Index(['id', 'OVD_t1', 'OVD_t2', 'OVD_t3', 'OVD_sum', 'pay_normal',
       'prod_code', 'prod_limit', 'update_date', 'new_balance',
       'highest_balance', 'report_date', 'label', 'fea_1', 'fea_2', 'fea_3',
       'fea_4', 'fea_5', 'fea_6', 'fea_7', 'fea_8', 'fea_9', 'fea_10',
       'fea_11'],
      dtype='object')

In [55]:
Payment_data.head(2)

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,highest_balance,report_date
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,NaN,NaN
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,491100.0,NaN

In [56]:
Customer_data.head(2)

,label,id,fea_1,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
0,1,54982665,5,1245.5,3,77000.0,2,15,5,109,5,151300,244.948974
1,0,59004779,4,1277.0,1,113000.0,2,8,-1,100,3,341759,207.173840

**Drop irrelevant columns**

In [57]:
df = df.drop(['id', 'update_date', 'report_date'], axis=1)

In [61]:
df.shape

(8250, 21)

**Handle missing values**

In [58]:
df = df.fillna(df.mean(numeric_only=True))

In [59]:
df.head(2)

,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,new_balance,highest_balance,label,...,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
0,0,0,0,0,1,10,16500.000000,0.0,219202.725928,0,...,1241.000000,3,62000.0,2,15,9,95,4,60023,1.000000
1,0,0,0,0,1,5,85789.702205,588720.0,491100.000000,1,...,1286.156813,2,126000.0,2,11,9,115,4,450028,224.267697

##5. Segregating the Payment dataset into Input & Output

In [62]:
X = df.drop('label', axis=1)
y = df['label']

In [63]:
x

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,...,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,...,1241.0,3,62000.0,2,15,9,95,4,60023,1.000000
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,...,NaN,2,126000.0,2,11,9,115,4,450028,224.267697
2,58997200,0,0,0,0,2,5,NaN,04/12/2016,840000.0,...,1376.0,1,150000.0,2,11,-1,110,4,60000,219.248717
3,54988608,0,0,0,0,3,10,37400.0,03/12/2016,8425.2,...,1214.0,3,60000.0,2,11,9,108,4,151300,158.113883
4,54987763,0,0,0,0,2,10,NaN,03/12/2016,15147.6,...,1232.0,1,96000.0,2,11,9,88,5,151300,233.520877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8245,58995478,0,0,0,0,9,15,NaN,NaN,0.0,...,1301.0,1,77000.0,2,11,5,95,3,450000,173.205081
8246,54992408,0,0,0,0,1,2,NaN,NaN,0.0,...,1314.5,1,53000.0,2,8,5,103,5,151300,187.539329
8247,54988209,0,0,0,0,5,13,NaN,NaN,20654.4,...,1305.5,3,93000.0,1,11,3,104,3,60032,200.000000
8248,54992408,0,0,0,0,1,2,NaN,NaN,0.0,...,1314.5,1,53000.0,2,8,5,103,5,151300,187.539329
8249,54989207,0,0,0,0,1,5,NaN,NaN,240000.0,...,NaN,2,49000.0,1,8,2,114,4,71000,180.280337

In [64]:
y

0       0
1       1
2       0
3       0
4       0
       ..
8245    0
8246    0
8247    0
8248    0
8249    1
Name: label, Length: 8250, dtype: int64

In [67]:

y = ['label']

In [142]:
x = df.drop(['label'], axis=1)

**Define Input (=x)  & Target (=y)**

In [119]:
x = df.iloc[:,].values
y = df['label']

In [143]:
x

,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,new_balance,highest_balance,fea_1,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
0,0,0,0,0,1,10,16500.000000,0.0,219202.725928,5,1241.000000,3,62000.0,2,15,9,95,4,60023,1.000000
1,0,0,0,0,1,5,85789.702205,588720.0,491100.000000,7,1286.156813,2,126000.0,2,11,9,115,4,450028,224.267697
2,0,0,0,0,2,5,85789.702205,840000.0,700500.000000,7,1376.000000,1,150000.0,2,11,-1,110,4,60000,219.248717
3,0,0,0,0,3,10,37400.000000,8425.2,7520.000000,7,1214.000000,3,60000.0,2,11,9,108,4,151300,158.113883
4,0,0,0,0,2,10,85789.702205,15147.6,219202.725928,7,1232.000000,1,96000.0,2,11,9,88,5,151300,233.520877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8245,0,0,0,0,9,15,85789.702205,0.0,219202.725928,7,1301.000000,1,77000.0,2,11,5,95,3,450000,173.205081
8246,0,0,0,0,1,2,85789.702205,0.0,219202.725928,4,1314.500000,1,53000.0,2,8,5,103,5,151300,187.539329
8247,0,0,0,0,5,13,85789.702205,20654.4,33315.000000,7,1305.500000,3,93000.0,1,11,3,104,3,60032,200.000000
8248,0,0,0,0,1,2,85789.702205,0.0,219202.725928,4,1314.500000,1,53000.0,2,8,5,103,5,151300,187.539329
8249,0,0,0,0,1,5,85789.702205,240000.0,200500.000000,4,1286.156813,2,49000.0,1,8,2,114,4,71000,180.280337

In [121]:
print(y.unique())

[0 1]

**✅ CLEAN - Remove non-numeric columns, all string columns**

##6. Performing Feature Scaling

In [ ]:
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#x_scaler = scaler.fit_transform(x)

##7. Splitting the dataset into Train and Test (no scaling)

In [144]:
from sklearn.model_selection import train_test_split

# x_train, x_test, y_train, y_test = train_test_split(x_scaler,y,test_size=0.2, random_state=42)

In [145]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [146]:
x_train.shape

(6600, 21)

In [124]:
x_test.shape

(1650, 21)

In [125]:
y_train.shape

(6600,)

In [126]:
y_test.shape

(1650,)

In [127]:
x.shape

(8250, 21)

In [128]:
y.shape

(8250,)

In [147]:
print("y_type:", type(y))
print("Unique values:", y.unique())
print("Sample y:", y[:10])

y_type: <class 'pandas.core.series.Series'>
Unique values: [0 1]
Sample y: 0    0
1    1
2    0
3    0
4    0
5    0
6    1
7    0
8    0
9    0
Name: label, dtype: int64

##8. Load & Train the Random Forest Classifier model

In [148]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42)

#model.fit(x_train, y_train)

In [149]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

##9. Prediciton
👉 Train = learn
👉 Test = evaluate

In [150]:
y_pred = model.predict(X_test)

In [151]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

##10. Evaluate

In [152]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9533333333333334

In [153]:
df.head(2)

,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,new_balance,highest_balance,label,...,fea_2,fea_3,fea_4,fea_5,fea_6,fea_7,fea_8,fea_9,fea_10,fea_11
0,0,0,0,0,1,10,16500.000000,0.0,219202.725928,0,...,1241.000000,3,62000.0,2,15,9,95,4,60023,1.000000
1,0,0,0,0,1,5,85789.702205,588720.0,491100.000000,1,...,1286.156813,2,126000.0,2,11,9,115,4,450028,224.267697

In [160]:
import pandas as pd


new_customer = pd.DataFrame([{
    'OVD_t1': 1,
    'OVD_t2': 0,
    'OVD_t3': 0,
    'OVD_sum': 1,
    'pay_normal': 1,
    'prod_code': 12,
    'prod_limit': 100000,
    'new_balance': 2000,
    'highest_balance': 7000,
    'fea_1': 1,
    'fea_2': 1,
    'fea_3': 1,
    'fea_4': 1,
    'fea_5': 1,
    'fea_6': 1,
    'fea_7': 1,
    'fea_8': 1,
    'fea_9': 1,
    'fea_10': 1,
    'fea_11': 1,}])

In [161]:
prediction = model.predict(new_customer)
print("Prediction Risk:", prediction)

Prediction Risk: [0]