<a href="https://colab.research.google.com/github/KS6Git/Python_EDA_Raja/blob/main/Random_Forest_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **RANDOM FOREST ASSIGNMENT**
Problem Statement:
This assignment aims to utilize Random Forest algorithms to analyze given datasets, extracting
meaningful insights, and predicting outcomes based on the decision rules learned from the data.
By exploring the datasets and employing Random Forest techniques, students are expected to
build predictive models and interpret the decision rules to derive valuable insights.

- Credit Risk Classification Dataset
https://www.kaggle.com/datasets/praveengovi/credit-risk-classification-dataset/data

##1. Importing necessary Libraries

In [3]:
import numpy as np
import pandas as pd

##2. Loading the Payment & Customer datasets
https://www.kaggle.com/datasets/praveengovi/credit-risk-classification-dataset/data

In [4]:
Payment_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Raja_Python_Programming/Random_Tree/payment_data.csv')

In [5]:
Cust_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Raja_Python_Programming/Random_Tree/customer_data.csv')

**payment_data.csv:**
  
**id:** customer id     
**OVD_t1:** number of times overdue type 1  
**OVD_t2:** number of times overdue type 2  
**OVD_t3:** number of times overdue type 3    
**OVD_sum:** total overdue days   
**pay_normal:** number of times normal payment  
**prod_code:** credit product code  
**prod_limit:** credit limit of product   
**update_date:** account update date  
**new_balance:** current balance of product   
**highest_balance:** highest balance in history   
**report_date:** date of recent payment   

**customer_data.csv:**                              
customer’s card payment history.
customer’s demographic data and category attributes which have been encoded.                             
Category features are
**fea_1, fea_3, fea_5, fea_6, fea_7, fea_9.**   
**label is 1**, the customer is in high credit risk   
**label is 0**, the customer is in low credit risk

In [5]:
Payment_data

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,highest_balance,report_date
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,NaN,NaN
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,491100.0,NaN
2,58997200,0,0,0,0,2,5,NaN,04/12/2016,840000.0,700500.0,22/04/2016
3,54988608,0,0,0,0,3,10,37400.0,03/12/2016,8425.2,7520.0,25/04/2016
4,54987763,0,0,0,0,2,10,NaN,03/12/2016,15147.6,NaN,26/04/2016
...,...,...,...,...,...,...,...,...,...,...,...,...
8245,58995478,0,0,0,0,9,15,NaN,NaN,0.0,NaN,NaN
8246,54992408,0,0,0,0,1,2,NaN,NaN,0.0,NaN,NaN
8247,54988209,0,0,0,0,5,13,NaN,NaN,20654.4,33315.0,NaN
8248,54992408,0,0,0,0,1,2,NaN,NaN,0.0,NaN,NaN
8249,54989207,0,0,0,0,1,5,NaN,NaN,240000.0,200500.0,NaN

##3. Summarising the Payment dataset

In [7]:
Payment_data.head(2)

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,highest_balance,report_date
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,NaN,NaN
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,491100.0,NaN

In [9]:
Payment_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8250 entries, 0 to 8249
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               8250 non-null   int64
 1   OVD_t1           8250 non-null   int64
 2   OVD_t2           8250 non-null   int64
 3   OVD_t3           8250 non-null   int64
 4   OVD_sum          8250 non-null   int64
 5   pay_normal       8250 non-null   int64
 6   prod_code        8250 non-null   int64
 7   prod_limit       2132 non-null   float64
 8   update_date      8224 non-null   object
 9   new_balance      8250 non-null   float64
 10  highest_balance  7841 non-null   float64
 11  report_date      7136 non-null   object
dtypes: float64(3), int64(7), object(2)
memory usage: 773.6+ KB

In [10]:
Payment_data.describe()

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,new_balance,highest_balance
count,8.250000e+03,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,2132.000000,8.250000e+03,7.841000e+03
mean,5.782173e+07,0.249091,0.127152,0.369212,187.681697,14.526667,8.232000,85789.702205,1.054042e+05,2.192027e+05
std,1.822724e+06,1.250197,0.860046,2.900320,1804.232570,12.053627,3.533055,74345.828184,1.887704e+06,2.814536e+06
min,5.498235e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.100000,-4.030320e+04,5.010000e+02
25%,5.499050e+07,0.000000,0.000000,0.000000,0.000000,4.000000,6.000000,37400.000000,0.000000e+00,2.345300e+04
50%,5.898905e+07,0.000000,0.000000,0.000000,0.000000,11.000000,10.000000,68200.000000,0.000000e+00,4.404700e+04
75%,5.899655e+07,0.000000,0.000000,0.000000,0.000000,25.000000,10.000000,112200.000000,2.494800e+04,1.005000e+05
max,5.900624e+07,34.000000,34.000000,35.000000,31500.000000,36.000000,27.000000,660000.000000,1.632120e+08,1.800005e+08

In [8]:
Payment_data.shape

(8250, 12)

In [12]:
Payment_data.keys()

Index(['id', 'OVD_t1', 'OVD_t2', 'OVD_t3', 'OVD_sum', 'pay_normal',
       'prod_code', 'prod_limit', 'update_date', 'new_balance',
       'highest_balance', 'report_date'],
      dtype='object')

##4. Pre-processing the Payment dataset

In [6]:
Payment_data.isnull().sum()

id                    0
OVD_t1                0
OVD_t2                0
OVD_t3                0
OVD_sum               0
pay_normal            0
prod_code             0
prod_limit         6118
update_date          26
new_balance           0
highest_balance     409
report_date        1114
dtype: int64

##5. Segregating the Payment dataset into Input & Output

In [15]:
x = Payment_data.iloc[:,:-1]
y = Payment_data.iloc[:,-1]

In [16]:
x

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,highest_balance
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,NaN
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,491100.0
2,58997200,0,0,0,0,2,5,NaN,04/12/2016,840000.0,700500.0
3,54988608,0,0,0,0,3,10,37400.0,03/12/2016,8425.2,7520.0
4,54987763,0,0,0,0,2,10,NaN,03/12/2016,15147.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...
8245,58995478,0,0,0,0,9,15,NaN,NaN,0.0,NaN
8246,54992408,0,0,0,0,1,2,NaN,NaN,0.0,NaN
8247,54988209,0,0,0,0,5,13,NaN,NaN,20654.4,33315.0
8248,54992408,0,0,0,0,1,2,NaN,NaN,0.0,NaN
8249,54989207,0,0,0,0,1,5,NaN,NaN,240000.0,200500.0

In [17]:
y

0              NaN
1              NaN
2       22/04/2016
3       25/04/2016
4       26/04/2016
           ...
8245           NaN
8246           NaN
8247           NaN
8248           NaN
8249           NaN
Name: report_date, Length: 8250, dtype: object

In [10]:
x = Payment_data.iloc[:,:-1].values
y = Payment_data.iloc[:,-1].values

In [11]:
x

array([[58987402, 0, 0, ..., '04/12/2016', 0.0, nan],
       [58995151, 0, 0, ..., '04/12/2016', 588720.0, 491100.0],
       [58997200, 0, 0, ..., '04/12/2016', 840000.0, 700500.0],
       ...,
       [54988209, 0, 0, ..., nan, 20654.4, 33315.0],
       [54992408, 0, 0, ..., nan, 0.0, nan],
       [54989207, 0, 0, ..., nan, 240000.0, 200500.0]], dtype=object)

In [12]:
y

array([nan, nan, '22/04/2016', ..., nan, nan, nan], dtype=object)

In [5]:
Payment_data.head(2)

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,update_date,new_balance,highest_balance,report_date
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,NaN,NaN
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,491100.0,NaN

**Remove non-numeric columns, all string columns**

In [7]:
Payment_data = Payment_data.select_dtypes(exclude=['object'])

In [7]:
Payment_data.head(2)

,id,OVD_t1,OVD_t2,OVD_t3,OVD_sum,pay_normal,prod_code,prod_limit,new_balance,highest_balance
0,58987402,0,0,0,0,1,10,16500.0,0.0,NaN
1,58995151,0,0,0,0,1,5,NaN,588720.0,491100.0

In [ ]:
# X = Payment_data.drop(['id','update_date','report_date'],axis=1)

In [8]:
# Segregate Input and Output again with 'string' columns removed
x = Payment_data.iloc[:,:-1].values
y = Payment_data.iloc[:,-1].values

##6. Performing Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaler = scaler.fit_transform(x)

In [10]:
x_scaler

array([[ 0.63956049, -0.19925346, -0.14785159, ...,  0.50044712,
        -0.93221045, -0.05584063],
       [ 0.64381207, -0.19925346, -0.14785159, ..., -0.91484452,
                nan,  0.25604918],
       [ 0.64493628, -0.19925346, -0.14785159, ..., -0.91484452,
                nan,  0.38917133],
       ...,
       [-1.55464747, -0.19925346, -0.14785159, ...,  1.34962211,
                nan, -0.04489842],
       [-1.55234363, -0.19925346, -0.14785159, ..., -1.7640195 ,
                nan, -0.05584063],
       [-1.5540999 , -0.19925346, -0.14785159, ..., -0.91484452,
                nan,  0.07130564]])

##7. Splitting the dataset into Train and Test

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaler,y,test_size=0.2, random_state=42)

In [11]:
x_train.shape

(6600, 9)

In [34]:
x_test.shape

(1650, 9)

In [35]:
y_train.shape

(6600,)

In [36]:
y_test.shape

(1650,)

In [37]:
x.shape

(8250, 9)

In [12]:
y.shape

(8250,)

##8. Loading the Random Forest model

In [13]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)

In [14]:
model

RandomForestClassifier()

##9. Train the model

In [15]:
import numpy as np
# Identify rows where y_train is not NaN
non_nan_mask = ~np.isnan(y_train.astype(float)) # Ensure y_train is treated as float for isnan check

# Filter x_train and y_train to remove NaN values from y_train
x_train_filtered = x_train[non_nan_mask]
y_train_filtered = y_train[non_nan_mask]

In [ ]:
# Now fit the model with the filtered data
model.fit(x_train_filtered, y_train_filtered)

## **NEED YOUR HELP - IT KEEPS CRASHING AT THIS POINT**